name: "Build & Release" # Name of the workflow
on: # Trigger for the workflow
  push: # Trigger on push events
    branches:
      - main # Only for the main branch
jobs:  # Telling what jobs we need to happen
  build:      # Specify the building name and machine
    name: Build & Release  # you can name the build whatever you want
    runs-on: macos-latest # here we selected macos-latest to be able to get ios build
    permissions: # Grant write permissions for creating releases and uploading artifacts
      contents: write
    steps:
      - name: Checkout Repository # Check out the code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0 # Needed for git tag check. Fetches all history and tags.

      - name: Set Up Java # Set up Java for Android builds
        uses: actions/setup-java@v4.7.0
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Set Up Flutter # Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.0'
          channel: 'stable'
          cache: true
      
      - name: Decode android/keystore.jks
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > /Users/runner/work/sailBlog-app/sailBlog-app/android/keystore.jks

      - name: Decode android/key.properties
        run: echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > /Users/runner/work/sailBlog-app/sailBlog-app/android/key.properties

      - name: Decode android/local.properties
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" | base64 --decode > /Users/runner/work/sailBlog-app/sailBlog-app/android/local.properties

      - name: Install Flutter dependencies # Install Flutter packages
        run: |
          flutter config --no-analytics --no-cli-animations
          flutter pub get

      - name: Build APK # Build the Android APK
        run: flutter build apk --release

      #- name: Build IPA # Build the iOS IPA (without code signing)
      #  run: flutter build ipa --no-codesign

      #- name: Compress Archives and IPAs # Compress the iOS build directory
      #  run: |
      #    cd build
      #    tar -czf ios_build.tar.gz ios

      - name: Extract version from pubspec.yaml # Extract the version number from the pubspec.yaml file
        id: extract_version
        run: |
          version=$(grep '^version: ' pubspec.yaml | cut -d ' ' -f 2 | tr -d '\r')
          echo "VERSION=$version" >> $GITHUB_ENV # Set the VERSION environment variable

      - name: Check if Tag Exists # Check if a Git tag with the current version exists
        id: check_tag
        run: |
          if git tag -l "v${{ env.VERSION }}" | grep -q "v${{ env.VERSION }}"; then # Check if tag exists
            echo "TAG_EXISTS=true" >> $GITHUB_ENV # Set TAG_EXISTS to true
          else
            echo "TAG_EXISTS=false" >> $GITHUB_ENV # Set TAG_EXISTS to false
          fi

      - name: Modify Tag (Tag Exists)
        if: env.TAG_EXISTS == 'true'
        id: modify_tag
        run: |
          date_time=$(date +'%Y%m%d%H%M%S')
          new_version="${{ env.VERSION }}+${date_time}"
          echo "VERSION=$new_version" >> $GITHUB_ENV
          echo "NEW_TAG_VERSION=$new_version" >> $GITHUB_ENV

      - name: Set Default Tag (Tag Does Not Exist)
        if: env.TAG_EXISTS == 'false'
        run: |
          echo "NEW_TAG_VERSION=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Rename APK # Rename the APK file to include the version
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/sailBlog_${{ env.NEW_TAG_VERSION }}.apk

      - name: Upload Artifacts # Upload the APK and iOS build as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Releases
          path: |
            build/app/outputs/flutter-apk/sailBlog_${{ env.NEW_TAG_VERSION }}.apk # Upload the renamed APK
       #     build/ios_build.tar.gz

      - name: Create Release # Create a GitHub release
        uses: ncipollo/release-action@v1.15.0
        with:
          artifacts: "build/app/outputs/flutter-apk/sailBlog_${{ env.NEW_TAG_VERSION }}.apk,build/ios_build.tar.gz" # Include the renamed APK in the release
          tag: v${{ env.NEW_TAG_VERSION }} # Use the version as the tag name
